object Versions {
    const val compose = "1.3.3"
    const val lottieCompose = "6.0.1"
    const val composeTooling = "1.3.3"
    const val activityCompose = "1.6.1"
    const val composeMaterial = "1.3.1"
    const val androidXJunit = "1.1.5"
    const val espresso = "3.5.1"
    const val jUnit = "4.13.2"
    const val androidXCore = "1.9.0"
    const val androidXLifecycle = "2.5.1"
    const val navigation = "2.5.3"
    const val leakCanaryVersion = "2.10"
    const val composeUITest = "1.3.3"
    const val daggerHilt = "2.44"
    const val hiltNavigationCompose = "1.0.0"
    const val composeLifecycle = "2.6.0-alpha05"
}